name: Build Legacy Logic

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  windows-x86_64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build -A x64 -DLOGIC2=OFF
        cmake --build ${{github.workspace}}/build --config Release
    - uses: actions/upload-artifact@v7
      with:
        name: legacy_windows_x86_64
        path: ${{github.workspace}}/build/Analyzers/Release/*.dll

  windows-arm64:
    runs-on: windows-11-arm
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build -A ARM64 -DLOGIC2=OFF
        cmake --build ${{github.workspace}}/build --config Release
    - uses: actions/upload-artifact@v7
      with:
        name: legacy_windows_arm64
        path: ${{github.workspace}}/build/Analyzers/Release/*.dll

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build/x86_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64 -DLOGIC2=OFF
        cmake --build ${{github.workspace}}/build/x86_64
        cmake -B ${{github.workspace}}/build/arm64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64 -DLOGIC2=OFF
        cmake --build ${{github.workspace}}/build/arm64
    - uses: actions/upload-artifact@v7
      with:
        name: legacy_macos_x86_64
        path: ${{github.workspace}}/build/x86_64/Analyzers/*.so
    - uses: actions/upload-artifact@v7
      with:
        name: legacy_macos_arm64
        path: ${{github.workspace}}/build/arm64/Analyzers/*.so

  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Pull builder image
      run: docker pull ghcr.io/saleae/analyzer-build-image:linux-x86_64
    - name: Build
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          ghcr.io/saleae/analyzer-build-image:linux-x86_64 \
          bash -c 'cmake -B build -DCMAKE_BUILD_TYPE=Release -DLOGIC2=OFF && cmake --build build'
    - uses: actions/upload-artifact@v7
      with:
        name: legacy_linux_x86_64
        path: ${{github.workspace}}/build/Analyzers/*.so

  linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v6
    - name: Pull builder image
      run: docker pull ghcr.io/saleae/analyzer-build-image:linux-arm64
    - name: Build
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          ghcr.io/saleae/analyzer-build-image:linux-arm64 \
          bash -c 'cmake -B build -DCMAKE_BUILD_TYPE=Release -DLOGIC2=OFF && cmake --build build'
    - uses: actions/upload-artifact@v7
      with:
        name: legacy_linux_arm64
        path: ${{github.workspace}}/build/Analyzers/*.so
